const seasonData = [
  {
    year: 2023,
    spring: {
      month: 2,
      day: 20,
      hour: 5,
      minute: 24,
      tod: "pm",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 21,
      hour: 10,
      minute: 57,
      tod: "am",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 23,
      hour: 2,
      minute: 50,
      tod: "am",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 21,
      hour: 10,
      minute: 27,
      tod: "pm",
      zone: "EST",
    },
  },
  {
    year: 2024,
    spring: {
      month: 2,
      day: 19,
      hour: 11,
      minute: 6,
      tod: "pm",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 20,
      hour: 4,
      minute: 50,
      tod: "pm",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 22,
      hour: 8,
      minute: 43,
      tod: "am",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 21,
      hour: 4,
      minute: 20,
      tod: "am",
      zone: "EST",
    },
  },
  {
    year: 2025,
    spring: {
      month: 2,
      day: 20,
      hour: 5,
      minute: 1,
      tod: "am",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 20,
      hour: 10,
      minute: 42,
      tod: "pm",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 22,
      hour: 2,
      minute: 19,
      tod: "pm",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 21,
      hour: 10,
      minute: 3,
      tod: "am",
      zone: "EST",
    },
  },
  {
    year: 2026,
    spring: {
      month: 2,
      day: 20,
      hour: 10,
      minute: 46,
      tod: "am",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 21,
      hour: 4,
      minute: 24,
      tod: "am",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 22,
      hour: 8,
      minute: 5,
      tod: "pm",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 21,
      hour: 3,
      minute: 50,
      tod: "pm",
      zone: "EST",
    },
  },
  {
    year: 2027,
    spring: {
      month: 2,
      day: 20,
      hour: 4,
      minute: 24,
      tod: "pm",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 21,
      hour: 10,
      minute: 10,
      tod: "am",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 23,
      hour: 2,
      minute: 1,
      tod: "am",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 21,
      hour: 9,
      minute: 42,
      tod: "pm",
      zone: "EST",
    },
  },
  {
    year: 2028,
    spring: {
      month: 2,
      day: 19,
      hour: 10,
      minute: 17,
      tod: "pm",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 20,
      hour: 4,
      minute: 1,
      tod: "pm",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 22,
      hour: 7,
      minute: 45,
      tod: "am",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 21,
      hour: 3,
      minute: 19,
      tod: "am",
      zone: "EST",
    },
  },
  {
    year: 2029,
    spring: {
      month: 2,
      day: 20,
      hour: 4,
      minute: 2,
      tod: "am",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 20,
      hour: 9,
      minute: 48,
      tod: "pm",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 22,
      hour: 1,
      minute: 38,
      tod: "pm",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 21,
      hour: 9,
      minute: 14,
      tod: "am",
      zone: "EST",
    },
  },
  {
    year: 2030,
    spring: {
      month: 2,
      day: 20,
      hour: 9,
      minute: 51,
      tod: "am",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 21,
      hour: 3,
      minute: 31,
      tod: "am",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 22,
      hour: 7,
      minute: 26,
      tod: "pm",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 21,
      hour: 3,
      minute: 9,
      tod: "pm",
      zone: "EST",
    },
  },
  {
    year: 2031,
    spring: {
      month: 2,
      day: 20,
      hour: 3,
      minute: 41,
      tod: "pm",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 21,
      hour: 9,
      minute: 17,
      tod: "am",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 23,
      hour: 1,
      minute: 15,
      tod: "am",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 21,
      hour: 8,
      minute: 55,
      tod: "pm",
      zone: "EST",
    },
  },
  {
    year: 2032,
    spring: {
      month: 2,
      day: 19,
      hour: 9,
      minute: 21,
      tod: "pm",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 20,
      hour: 3,
      minute: 8,
      tod: "pm",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 22,
      hour: 7,
      minute: 10,
      tod: "am",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 21,
      hour: 2,
      minute: 55,
      tod: "am",
      zone: "EST",
    },
  },
  {
    year: 2033,
    spring: {
      month: 2,
      day: 20,
      hour: 3,
      minute: 22,
      tod: "am",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 20,
      hour: 9,
      minute: 1,
      tod: "pm",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 22,
      hour: 12,
      minute: 51,
      tod: "pm",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 21,
      hour: 8,
      minute: 45,
      tod: "am",
      zone: "EST",
    },
  },
  {
    year: 2034,
    spring: {
      month: 2,
      day: 20,
      hour: 9,
      minute: 17,
      tod: "am",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 21,
      hour: 2,
      minute: 44,
      tod: "am",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 22,
      hour: 6,
      minute: 39,
      tod: "pm",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 21,
      hour: 2,
      minute: 33,
      tod: "pm",
      zone: "EST",
    },
  },
  {
    year: 2035,
    spring: {
      month: 2,
      day: 20,
      hour: 3,
      minute: 2,
      tod: "pm",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 21,
      hour: 8,
      minute: 33,
      tod: "am",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 23,
      hour: 12,
      minute: 39,
      tod: "am",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 21,
      hour: 8,
      minute: 30,
      tod: "pm",
      zone: "EST",
    },
  },
  {
    year: 2036,
    spring: {
      month: 2,
      day: 19,
      hour: 9,
      minute: 2,
      tod: "pm",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 20,
      hour: 2,
      minute: 32,
      tod: "pm",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 22,
      hour: 6,
      minute: 23,
      tod: "am",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 21,
      hour: 2,
      minute: 12,
      tod: "am",
      zone: "EST",
    },
  },
  {
    year: 2037,
    spring: {
      month: 2,
      day: 20,
      hour: 2,
      minute: 50,
      tod: "am",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 20,
      hour: 8,
      minute: 22,
      tod: "pm",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 22,
      hour: 12,
      minute: 13,
      tod: "pm",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 21,
      hour: 8,
      minute: 7,
      tod: "am",
      zone: "EST",
    },
  },
  {
    year: 2038,
    spring: {
      month: 2,
      day: 20,
      hour: 8,
      minute: 40,
      tod: "am",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 21,
      hour: 2,
      minute: 9,
      tod: "am",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 22,
      hour: 6,
      minute: 2,
      tod: "pm",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 21,
      hour: 2,
      minute: 2,
      tod: "pm",
      zone: "EST",
    },
  },
  {
    year: 2039,
    spring: {
      month: 2,
      day: 20,
      hour: 2,
      minute: 31,
      tod: "pm",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 21,
      hour: 7,
      minute: 57,
      tod: "am",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 22,
      hour: 11,
      minute: 49,
      tod: "pm",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 21,
      hour: 7,
      minute: 40,
      tod: "pm",
      zone: "EST",
    },
  },
  {
    year: 2040,
    spring: {
      month: 2,
      day: 19,
      hour: 8,
      minute: 11,
      tod: "pm",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 20,
      hour: 1,
      minute: 46,
      tod: "pm",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 22,
      hour: 5,
      minute: 44,
      tod: "am",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 21,
      hour: 1,
      minute: 32,
      tod: "am",
      zone: "EST",
    },
  },
  {
    year: 2041,
    spring: {
      month: 2,
      day: 20,
      hour: 2,
      minute: 6,
      tod: "am",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 20,
      hour: 7,
      minute: 35,
      tod: "pm",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 22,
      hour: 11,
      minute: 26,
      tod: "am",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 21,
      hour: 7,
      minute: 18,
      tod: "am",
      zone: "EST",
    },
  },
  {
    year: 2042,
    spring: {
      month: 2,
      day: 20,
      hour: 7,
      minute: 53,
      tod: "am",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 21,
      hour: 1,
      minute: 15,
      tod: "am",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 22,
      hour: 5,
      minute: 11,
      tod: "pm",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 21,
      hour: 1,
      minute: 4,
      tod: "pm",
      zone: "EST",
    },
  },
  {
    year: 2043,
    spring: {
      month: 2,
      day: 20,
      hour: 1,
      minute: 27,
      tod: "pm",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 21,
      hour: 6,
      minute: 58,
      tod: "am",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 22,
      hour: 11,
      minute: 6,
      tod: "pm",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 21,
      hour: 7,
      minute: 1,
      tod: "pm",
      zone: "EST",
    },
  },
  {
    year: 2044,
    spring: {
      month: 2,
      day: 19,
      hour: 7,
      minute: 20,
      tod: "pm",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 20,
      hour: 12,
      minute: 51,
      tod: "pm",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 22,
      hour: 4,
      minute: 47,
      tod: "am",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 21,
      hour: 12,
      minute: 43,
      tod: "am",
      zone: "EST",
    },
  },
  {
    year: 2045,
    spring: {
      month: 2,
      day: 20,
      hour: 1,
      minute: 7,
      tod: "am",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 20,
      hour: 6,
      minute: 33,
      tod: "pm",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 22,
      hour: 10,
      minute: 32,
      tod: "am",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 21,
      hour: 6,
      minute: 35,
      tod: "am",
      zone: "EST",
    },
  },
  {
    year: 2046,
    spring: {
      month: 2,
      day: 20,
      hour: 6,
      minute: 57,
      tod: "am",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 21,
      hour: 12,
      minute: 14,
      tod: "am",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 22,
      hour: 4,
      minute: 21,
      tod: "pm",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 21,
      hour: 12,
      minute: 28,
      tod: "pm",
      zone: "EST",
    },
  },
  {
    year: 2047,
    spring: {
      month: 2,
      day: 20,
      hour: 12,
      minute: 52,
      tod: "pm",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 21,
      hour: 6,
      minute: 3,
      tod: "am",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 22,
      hour: 10,
      minute: 8,
      tod: "pm",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 21,
      hour: 6,
      minute: 7,
      tod: "pm",
      zone: "EST",
    },
  },
  {
    year: 2048,
    spring: {
      month: 2,
      day: 19,
      hour: 6,
      minute: 33,
      tod: "pm",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 20,
      hour: 11,
      minute: 53,
      tod: "am",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 22,
      hour: 4,
      minute: 0,
      tod: "am",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 21,
      hour: 12,
      minute: 2,
      tod: "am",
      zone: "EST",
    },
  },
  {
    year: 2049,
    spring: {
      month: 2,
      day: 20,
      hour: 12,
      minute: 28,
      tod: "am",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 20,
      hour: 5,
      minute: 47,
      tod: "pm",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 22,
      hour: 9,
      minute: 42,
      tod: "am",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 21,
      hour: 5,
      minute: 52,
      tod: "am",
      zone: "EST",
    },
  },
  {
    year: 2050,
    spring: {
      month: 2,
      day: 20,
      hour: 6,
      minute: 19,
      tod: "am",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 20,
      hour: 11,
      minute: 33,
      tod: "pm",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 22,
      hour: 3,
      minute: 28,
      tod: "pm",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 21,
      hour: 11,
      minute: 38,
      tod: "am",
      zone: "EST",
    },
  },
  {
    year: 2051,
    spring: {
      month: 2,
      day: 20,
      hour: 11,
      minute: 59,
      tod: "am",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 21,
      hour: 5,
      minute: 18,
      tod: "am",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 22,
      hour: 9,
      minute: 27,
      tod: "pm",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 21,
      hour: 5,
      minute: 34,
      tod: "pm",
      zone: "EST",
    },
  },
  {
    year: 2052,
    spring: {
      month: 2,
      day: 19,
      hour: 5,
      minute: 56,
      tod: "pm",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 20,
      hour: 11,
      minute: 16,
      tod: "am",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 22,
      hour: 3,
      minute: 15,
      tod: "am",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 20,
      hour: 11,
      minute: 17,
      tod: "pm",
      zone: "EST",
    },
  },
  {
    year: 2053,
    spring: {
      month: 2,
      day: 19,
      hour: 11,
      minute: 47,
      tod: "pm",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 20,
      hour: 5,
      minute: 4,
      tod: "pm",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 22,
      hour: 9,
      minute: 6,
      tod: "am",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 21,
      hour: 5,
      minute: 10,
      tod: "am",
      zone: "EST",
    },
  },
  {
    year: 2054,
    spring: {
      month: 2,
      day: 20,
      hour: 5,
      minute: 34,
      tod: "am",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 20,
      hour: 10,
      minute: 47,
      tod: "pm",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 22,
      hour: 2,
      minute: 59,
      tod: "pm",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 21,
      hour: 11,
      minute: 10,
      tod: "am",
      zone: "EST",
    },
  },
  {
    year: 2055,
    spring: {
      month: 2,
      day: 20,
      hour: 11,
      minute: 28,
      tod: "am",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 21,
      hour: 4,
      minute: 40,
      tod: "am",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 22,
      hour: 8,
      minute: 48,
      tod: "pm",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 21,
      hour: 4,
      minute: 55,
      tod: "pm",
      zone: "EST",
    },
  },
  {
    year: 2056,
    spring: {
      month: 2,
      day: 19,
      hour: 5,
      minute: 11,
      tod: "pm",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 20,
      hour: 10,
      minute: 28,
      tod: "am",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 22,
      hour: 2,
      minute: 39,
      tod: "am",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 20,
      hour: 10,
      minute: 51,
      tod: "pm",
      zone: "EST",
    },
  },
  {
    year: 2057,
    spring: {
      month: 2,
      day: 19,
      hour: 11,
      minute: 8,
      tod: "pm",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 20,
      hour: 4,
      minute: 19,
      tod: "pm",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 22,
      hour: 8,
      minute: 23,
      tod: "am",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 21,
      hour: 4,
      minute: 43,
      tod: "am",
      zone: "EST",
    },
  },
  {
    year: 2058,
    spring: {
      month: 2,
      day: 20,
      hour: 5,
      minute: 5,
      tod: "am",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 20,
      hour: 10,
      minute: 4,
      tod: "pm",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 22,
      hour: 2,
      minute: 8,
      tod: "pm",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 21,
      hour: 10,
      minute: 25,
      tod: "am",
      zone: "EST",
    },
  },
  {
    year: 2059,
    spring: {
      month: 2,
      day: 20,
      hour: 10,
      minute: 44,
      tod: "am",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 21,
      hour: 3,
      minute: 47,
      tod: "am",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 22,
      hour: 8,
      minute: 3,
      tod: "pm",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 21,
      hour: 4,
      minute: 18,
      tod: "pm",
      zone: "EST",
    },
  },
  {
    year: 2060,
    spring: {
      month: 2,
      day: 19,
      hour: 4,
      minute: 38,
      tod: "pm",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 20,
      hour: 9,
      minute: 45,
      tod: "am",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 22,
      hour: 1,
      minute: 48,
      tod: "am",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 20,
      hour: 10,
      minute: 1,
      tod: "pm",
      zone: "EST",
    },
  },
  {
    year: 2061,
    spring: {
      month: 2,
      day: 19,
      hour: 10,
      minute: 26,
      tod: "pm",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 20,
      hour: 3,
      minute: 32,
      tod: "pm",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 22,
      hour: 7,
      minute: 31,
      tod: "am",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 21,
      hour: 3,
      minute: 49,
      tod: "am",
      zone: "EST",
    },
  },
  {
    year: 2062,
    spring: {
      month: 2,
      day: 20,
      hour: 4,
      minute: 7,
      tod: "am",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 20,
      hour: 9,
      minute: 11,
      tod: "pm",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 22,
      hour: 1,
      minute: 20,
      tod: "pm",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 21,
      hour: 9,
      minute: 43,
      tod: "am",
      zone: "EST",
    },
  },
  {
    year: 2063,
    spring: {
      month: 2,
      day: 20,
      hour: 9,
      minute: 59,
      tod: "am",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 21,
      hour: 3,
      minute: 2,
      tod: "am",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 22,
      hour: 7,
      minute: 8,
      tod: "pm",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 21,
      hour: 3,
      minute: 21,
      tod: "pm",
      zone: "EST",
    },
  },
  {
    year: 2064,
    spring: {
      month: 2,
      day: 19,
      hour: 3,
      minute: 39,
      tod: "pm",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 20,
      hour: 8,
      minute: 46,
      tod: "am",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 22,
      hour: 12,
      minute: 57,
      tod: "am",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 20,
      hour: 9,
      minute: 9,
      tod: "pm",
      zone: "EST",
    },
  },
  {
    year: 2065,
    spring: {
      month: 2,
      day: 19,
      hour: 9,
      minute: 28,
      tod: "pm",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 20,
      hour: 2,
      minute: 32,
      tod: "pm",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 22,
      hour: 6,
      minute: 42,
      tod: "am",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 21,
      hour: 3,
      minute: 1,
      tod: "am",
      zone: "EST",
    },
  },
  {
    year: 2066,
    spring: {
      month: 2,
      day: 20,
      hour: 3,
      minute: 20,
      tod: "am",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 20,
      hour: 8,
      minute: 16,
      tod: "pm",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 22,
      hour: 12,
      minute: 27,
      tod: "pm",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 21,
      hour: 8,
      minute: 46,
      tod: "am",
      zone: "EST",
    },
  },
  {
    year: 2067,
    spring: {
      month: 2,
      day: 20,
      hour: 8,
      minute: 54,
      tod: "am",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 21,
      hour: 1,
      minute: 56,
      tod: "am",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 22,
      hour: 6,
      minute: 20,
      tod: "pm",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 21,
      hour: 2,
      minute: 43,
      tod: "pm",
      zone: "EST",
    },
  },
  {
    year: 2068,
    spring: {
      month: 2,
      day: 19,
      hour: 2,
      minute: 49,
      tod: "pm",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 20,
      hour: 7,
      minute: 54,
      tod: "am",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 22,
      hour: 12,
      minute: 7,
      tod: "am",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 20,
      hour: 8,
      minute: 33,
      tod: "pm",
      zone: "EST",
    },
  },
  {
    year: 2069,
    spring: {
      month: 2,
      day: 19,
      hour: 8,
      minute: 45,
      tod: "pm",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 20,
      hour: 1,
      minute: 41,
      tod: "pm",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 22,
      hour: 5,
      minute: 52,
      tod: "am",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 21,
      hour: 2,
      minute: 22,
      tod: "am",
      zone: "EST",
    },
  },
  {
    year: 2070,
    spring: {
      month: 2,
      day: 20,
      hour: 2,
      minute: 35,
      tod: "am",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 20,
      hour: 7,
      minute: 23,
      tod: "pm",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 22,
      hour: 11,
      minute: 45,
      tod: "am",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 21,
      hour: 8,
      minute: 19,
      tod: "am",
      zone: "EST",
    },
  },
  {
    year: 2071,
    spring: {
      month: 2,
      day: 20,
      hour: 8,
      minute: 35,
      tod: "am",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 21,
      hour: 1,
      minute: 21,
      tod: "am",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 22,
      hour: 5,
      minute: 38,
      tod: "pm",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 21,
      hour: 2,
      minute: 4,
      tod: "pm",
      zone: "EST",
    },
  },
  {
    year: 2072,
    spring: {
      month: 2,
      day: 19,
      hour: 2,
      minute: 21,
      tod: "pm",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 20,
      hour: 7,
      minute: 14,
      tod: "am",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 21,
      hour: 11,
      minute: 28,
      tod: "pm",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 20,
      hour: 7,
      minute: 56,
      tod: "pm",
      zone: "EST",
    },
  },
  {
    year: 2073,
    spring: {
      month: 2,
      day: 19,
      hour: 8,
      minute: 13,
      tod: "pm",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 20,
      hour: 1,
      minute: 7,
      tod: "pm",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 22,
      hour: 5,
      minute: 16,
      tod: "am",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 21,
      hour: 1,
      minute: 51,
      tod: "am",
      zone: "EST",
    },
  },
  {
    year: 2074,
    spring: {
      month: 2,
      day: 20,
      hour: 2,
      minute: 9,
      tod: "am",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 20,
      hour: 6,
      minute: 59,
      tod: "pm",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 22,
      hour: 11,
      minute: 4,
      tod: "am",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 21,
      hour: 7,
      minute: 35,
      tod: "am",
      zone: "EST",
    },
  },
  {
    year: 2075,
    spring: {
      month: 2,
      day: 20,
      hour: 7,
      minute: 47,
      tod: "am",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 21,
      hour: 12,
      minute: 41,
      tod: "am",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 22,
      hour: 4,
      minute: 59,
      tod: "pm",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 21,
      hour: 1,
      minute: 27,
      tod: "pm",
      zone: "EST",
    },
  },
  {
    year: 2076,
    spring: {
      month: 2,
      day: 19,
      hour: 1,
      minute: 39,
      tod: "pm",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 20,
      hour: 6,
      minute: 37,
      tod: "am",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 21,
      hour: 10,
      minute: 50,
      tod: "pm",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 20,
      hour: 7,
      minute: 14,
      tod: "pm",
      zone: "EST",
    },
  },
  {
    year: 2077,
    spring: {
      month: 2,
      day: 19,
      hour: 7,
      minute: 31,
      tod: "pm",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 20,
      hour: 12,
      minute: 24,
      tod: "pm",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 22,
      hour: 4,
      minute: 36,
      tod: "am",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 21,
      hour: 1,
      minute: 1,
      tod: "am",
      zone: "EST",
    },
  },
  {
    year: 2078,
    spring: {
      month: 2,
      day: 20,
      hour: 1,
      minute: 11,
      tod: "am",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 20,
      hour: 5,
      minute: 58,
      tod: "pm",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 22,
      hour: 10,
      minute: 25,
      tod: "am",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 21,
      hour: 6,
      minute: 58,
      tod: "am",
      zone: "EST",
    },
  },
  {
    year: 2079,
    spring: {
      month: 2,
      day: 20,
      hour: 7,
      minute: 1,
      tod: "am",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 20,
      hour: 11,
      minute: 50,
      tod: "pm",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 22,
      hour: 4,
      minute: 13,
      tod: "pm",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 21,
      hour: 12,
      minute: 44,
      tod: "pm",
      zone: "EST",
    },
  },
  {
    year: 2080,
    spring: {
      month: 2,
      day: 19,
      hour: 12,
      minute: 44,
      tod: "pm",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 20,
      hour: 5,
      minute: 34,
      tod: "am",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 21,
      hour: 9,
      minute: 57,
      tod: "pm",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 20,
      hour: 6,
      minute: 33,
      tod: "pm",
      zone: "EST",
    },
  },
  {
    year: 2081,
    spring: {
      month: 2,
      day: 19,
      hour: 6,
      minute: 35,
      tod: "pm",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 20,
      hour: 11,
      minute: 17,
      tod: "am",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 22,
      hour: 3,
      minute: 38,
      tod: "am",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 21,
      hour: 12,
      minute: 23,
      tod: "am",
      zone: "EST",
    },
  },
  {
    year: 2082,
    spring: {
      month: 2,
      day: 20,
      hour: 12,
      minute: 31,
      tod: "am",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 20,
      hour: 5,
      minute: 4,
      tod: "pm",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 22,
      hour: 9,
      minute: 23,
      tod: "am",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 21,
      hour: 6,
      minute: 5,
      tod: "am",
      zone: "EST",
    },
  },
  {
    year: 2083,
    spring: {
      month: 2,
      day: 20,
      hour: 6,
      minute: 11,
      tod: "am",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 20,
      hour: 10,
      minute: 44,
      tod: "pm",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 22,
      hour: 3,
      minute: 12,
      tod: "pm",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 21,
      hour: 11,
      minute: 54,
      tod: "am",
      zone: "EST",
    },
  },
  {
    year: 2084,
    spring: {
      month: 2,
      day: 19,
      hour: 12,
      minute: 0,
      tod: "pm",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 20,
      hour: 4,
      minute: 41,
      tod: "am",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 21,
      hour: 9,
      minute: 0,
      tod: "pm",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 20,
      hour: 5,
      minute: 42,
      tod: "pm",
      zone: "EST",
    },
  },
  {
    year: 2085,
    spring: {
      month: 2,
      day: 19,
      hour: 5,
      minute: 54,
      tod: "pm",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 20,
      hour: 10,
      minute: 33,
      tod: "am",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 22,
      hour: 2,
      minute: 44,
      tod: "am",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 20,
      hour: 11,
      minute: 29,
      tod: "pm",
      zone: "EST",
    },
  },
  {
    year: 2086,
    spring: {
      month: 2,
      day: 19,
      hour: 11,
      minute: 36,
      tod: "pm",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 20,
      hour: 4,
      minute: 10,
      tod: "pm",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 22,
      hour: 8,
      minute: 33,
      tod: "am",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 21,
      hour: 5,
      minute: 23,
      tod: "am",
      zone: "EST",
    },
  },
  {
    year: 2087,
    spring: {
      month: 2,
      day: 20,
      hour: 5,
      minute: 29,
      tod: "am",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 20,
      hour: 10,
      minute: 7,
      tod: "pm",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 22,
      hour: 2,
      minute: 29,
      tod: "pm",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 21,
      hour: 11,
      minute: 9,
      tod: "am",
      zone: "EST",
    },
  },
  {
    year: 2088,
    spring: {
      month: 2,
      day: 19,
      hour: 11,
      minute: 18,
      tod: "am",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 20,
      hour: 3,
      minute: 57,
      tod: "am",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 21,
      hour: 8,
      minute: 19,
      tod: "pm",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 20,
      hour: 4,
      minute: 57,
      tod: "pm",
      zone: "EST",
    },
  },
  {
    year: 2089,
    spring: {
      month: 2,
      day: 19,
      hour: 5,
      minute: 7,
      tod: "pm",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 20,
      hour: 9,
      minute: 44,
      tod: "am",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 22,
      hour: 2,
      minute: 8,
      tod: "am",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 20,
      hour: 10,
      minute: 53,
      tod: "pm",
      zone: "EST",
    },
  },
  {
    year: 2090,
    spring: {
      month: 2,
      day: 19,
      hour: 11,
      minute: 3,
      tod: "pm",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 20,
      hour: 3,
      minute: 37,
      tod: "pm",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 22,
      hour: 8,
      minute: 0,
      tod: "am",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 21,
      hour: 4,
      minute: 44,
      tod: "am",
      zone: "EST",
    },
  },
  {
    year: 2091,
    spring: {
      month: 2,
      day: 20,
      hour: 4,
      minute: 43,
      tod: "am",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 20,
      hour: 9,
      minute: 20,
      tod: "pm",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 22,
      hour: 1,
      minute: 52,
      tod: "pm",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 21,
      hour: 10,
      minute: 39,
      tod: "am",
      zone: "EST",
    },
  },
  {
    year: 2092,
    spring: {
      month: 2,
      day: 19,
      hour: 10,
      minute: 34,
      tod: "am",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 20,
      hour: 3,
      minute: 16,
      tod: "am",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 21,
      hour: 7,
      minute: 43,
      tod: "pm",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 20,
      hour: 4,
      minute: 33,
      tod: "pm",
      zone: "EST",
    },
  },
  {
    year: 2093,
    spring: {
      month: 2,
      day: 19,
      hour: 4,
      minute: 36,
      tod: "pm",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 20,
      hour: 9,
      minute: 8,
      tod: "am",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 22,
      hour: 1,
      minute: 30,
      tod: "am",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 20,
      hour: 10,
      minute: 22,
      tod: "pm",
      zone: "EST",
    },
  },
  {
    year: 2094,
    spring: {
      month: 2,
      day: 19,
      hour: 10,
      minute: 22,
      tod: "pm",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 20,
      hour: 2,
      minute: 43,
      tod: "pm",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 22,
      hour: 7,
      minute: 18,
      tod: "am",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 21,
      hour: 4,
      minute: 14,
      tod: "am",
      zone: "EST",
    },
  },
  {
    year: 2095,
    spring: {
      month: 2,
      day: 20,
      hour: 4,
      minute: 16,
      tod: "am",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 20,
      hour: 8,
      minute: 40,
      tod: "pm",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 22,
      hour: 1,
      minute: 12,
      tod: "pm",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 21,
      hour: 10,
      minute: 2,
      tod: "am",
      zone: "EST",
    },
  },
  {
    year: 2096,
    spring: {
      month: 2,
      day: 19,
      hour: 10,
      minute: 4,
      tod: "am",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 20,
      hour: 2,
      minute: 32,
      tod: "am",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 21,
      hour: 6,
      minute: 56,
      tod: "pm",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 20,
      hour: 3,
      minute: 47,
      tod: "pm",
      zone: "EST",
    },
  },
  {
    year: 2097,
    spring: {
      month: 2,
      day: 19,
      hour: 3,
      minute: 49,
      tod: "pm",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 20,
      hour: 8,
      minute: 14,
      tod: "am",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 22,
      hour: 12,
      minute: 37,
      tod: "am",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 20,
      hour: 9,
      minute: 38,
      tod: "pm",
      zone: "EST",
    },
  },
  {
    year: 2098,
    spring: {
      month: 2,
      day: 19,
      hour: 9,
      minute: 41,
      tod: "pm",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 20,
      hour: 2,
      minute: 4,
      tod: "pm",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 22,
      hour: 6,
      minute: 25,
      tod: "am",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 21,
      hour: 3,
      minute: 22,
      tod: "am",
      zone: "EST",
    },
  },
  {
    year: 2099,
    spring: {
      month: 2,
      day: 20,
      hour: 3,
      minute: 19,
      tod: "am",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 20,
      hour: 7,
      minute: 43,
      tod: "pm",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 22,
      hour: 12,
      minute: 12,
      tod: "pm",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 21,
      hour: 9,
      minute: 5,
      tod: "am",
      zone: "EST",
    },
  },
  {
    year: 2100,
    spring: {
      month: 2,
      day: 20,
      hour: 9,
      minute: 5,
      tod: "am",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 21,
      hour: 1,
      minute: 33,
      tod: "am",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 22,
      hour: 6,
      minute: 1,
      tod: "pm",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 21,
      hour: 2,
      minute: 52,
      tod: "pm",
      zone: "EST",
    },
  },
  {
    year: 2101,
    spring: {
      month: 2,
      day: 20,
      hour: 2,
      minute: 58,
      tod: "pm",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 21,
      hour: 7,
      minute: 23,
      tod: "am",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 22,
      hour: 11,
      minute: 48,
      tod: "pm",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 21,
      hour: 8,
      minute: 40,
      tod: "pm",
      zone: "EST",
    },
  },
  {
    year: 2102,
    spring: {
      month: 2,
      day: 20,
      hour: 8,
      minute: 37,
      tod: "pm",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 21,
      hour: 12,
      minute: 55,
      tod: "pm",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 23,
      hour: 5,
      minute: 32,
      tod: "am",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 22,
      hour: 2,
      minute: 34,
      tod: "am",
      zone: "EST",
    },
  },
  {
    year: 2103,
    spring: {
      month: 2,
      day: 21,
      hour: 2,
      minute: 24,
      tod: "am",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 21,
      hour: 6,
      minute: 47,
      tod: "pm",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 23,
      hour: 11,
      minute: 26,
      tod: "am",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 22,
      hour: 8,
      minute: 25,
      tod: "am",
      zone: "EST",
    },
  },
  {
    year: 2104,
    spring: {
      month: 2,
      day: 20,
      hour: 8,
      minute: 15,
      tod: "am",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 21,
      hour: 12,
      minute: 39,
      tod: "am",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 22,
      hour: 5,
      minute: 11,
      tod: "pm",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 21,
      hour: 2,
      minute: 14,
      tod: "pm",
      zone: "EST",
    },
  },
  {
    year: 2105,
    spring: {
      month: 2,
      day: 20,
      hour: 2,
      minute: 8,
      tod: "pm",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 21,
      hour: 6,
      minute: 20,
      tod: "am",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 22,
      hour: 10,
      minute: 53,
      tod: "pm",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 21,
      hour: 8,
      minute: 5,
      tod: "pm",
      zone: "EST",
    },
  },
  {
    year: 2106,
    spring: {
      month: 2,
      day: 20,
      hour: 8,
      minute: 5,
      tod: "pm",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 21,
      hour: 12,
      minute: 14,
      tod: "pm",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 23,
      hour: 4,
      minute: 48,
      tod: "am",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 22,
      hour: 1,
      minute: 54,
      tod: "am",
      zone: "EST",
    },
  },
  {
    year: 2107,
    spring: {
      month: 2,
      day: 21,
      hour: 1,
      minute: 51,
      tod: "am",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 21,
      hour: 6,
      minute: 2,
      tod: "pm",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 23,
      hour: 10,
      minute: 38,
      tod: "am",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 22,
      hour: 7,
      minute: 44,
      tod: "am",
      zone: "EST",
    },
  },
  {
    year: 2108,
    spring: {
      month: 2,
      day: 20,
      hour: 7,
      minute: 40,
      tod: "am",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 20,
      hour: 11,
      minute: 59,
      tod: "pm",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 22,
      hour: 4,
      minute: 30,
      tod: "pm",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 21,
      hour: 1,
      minute: 36,
      tod: "pm",
      zone: "EST",
    },
  },
  {
    year: 2109,
    spring: {
      month: 2,
      day: 20,
      hour: 1,
      minute: 38,
      tod: "pm",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 21,
      hour: 5,
      minute: 56,
      tod: "am",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 22,
      hour: 10,
      minute: 20,
      tod: "pm",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 21,
      hour: 7,
      minute: 29,
      tod: "pm",
      zone: "EST",
    },
  },
  {
    year: 2110,
    spring: {
      month: 2,
      day: 20,
      hour: 7,
      minute: 23,
      tod: "pm",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 21,
      hour: 11,
      minute: 34,
      tod: "am",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 23,
      hour: 4,
      minute: 8,
      tod: "am",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 22,
      hour: 1,
      minute: 20,
      tod: "am",
      zone: "EST",
    },
  },
  {
    year: 2111,
    spring: {
      month: 2,
      day: 21,
      hour: 1,
      minute: 12,
      tod: "am",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 21,
      hour: 5,
      minute: 27,
      tod: "pm",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 23,
      hour: 10,
      minute: 7,
      tod: "am",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 22,
      hour: 7,
      minute: 9,
      tod: "am",
      zone: "EST",
    },
  },
  {
    year: 2112,
    spring: {
      month: 2,
      day: 20,
      hour: 7,
      minute: 4,
      tod: "am",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 20,
      hour: 11,
      minute: 21,
      tod: "pm",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 22,
      hour: 3,
      minute: 57,
      tod: "pm",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 21,
      hour: 12,
      minute: 58,
      tod: "pm",
      zone: "EST",
    },
  },
  {
    year: 2113,
    spring: {
      month: 2,
      day: 20,
      hour: 12,
      minute: 52,
      tod: "pm",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 21,
      hour: 4,
      minute: 59,
      tod: "am",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 22,
      hour: 9,
      minute: 37,
      tod: "pm",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 21,
      hour: 6,
      minute: 48,
      tod: "pm",
      zone: "EST",
    },
  },
  {
    year: 2114,
    spring: {
      month: 2,
      day: 20,
      hour: 6,
      minute: 41,
      tod: "pm",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 21,
      hour: 10,
      minute: 48,
      tod: "am",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 23,
      hour: 3,
      minute: 29,
      tod: "am",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 22,
      hour: 12,
      minute: 41,
      tod: "am",
      zone: "EST",
    },
  },
  {
    year: 2115,
    spring: {
      month: 2,
      day: 21,
      hour: 12,
      minute: 24,
      tod: "am",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 21,
      hour: 4,
      minute: 32,
      tod: "pm",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 23,
      hour: 9,
      minute: 14,
      tod: "am",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 22,
      hour: 6,
      minute: 28,
      tod: "am",
      zone: "EST",
    },
  },
  {
    year: 2116,
    spring: {
      month: 2,
      day: 20,
      hour: 6,
      minute: 10,
      tod: "am",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 20,
      hour: 10,
      minute: 19,
      tod: "pm",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 22,
      hour: 2,
      minute: 58,
      tod: "pm",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 21,
      hour: 12,
      minute: 16,
      tod: "pm",
      zone: "EST",
    },
  },
  {
    year: 2117,
    spring: {
      month: 2,
      day: 20,
      hour: 12,
      minute: 8,
      tod: "pm",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 21,
      hour: 4,
      minute: 11,
      tod: "am",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 22,
      hour: 8,
      minute: 46,
      tod: "pm",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 21,
      hour: 6,
      minute: 5,
      tod: "pm",
      zone: "EST",
    },
  },
  {
    year: 2118,
    spring: {
      month: 2,
      day: 20,
      hour: 5,
      minute: 54,
      tod: "pm",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 21,
      hour: 9,
      minute: 45,
      tod: "am",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 23,
      hour: 2,
      minute: 28,
      tod: "am",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 21,
      hour: 11,
      minute: 50,
      tod: "pm",
      zone: "EST",
    },
  },
  {
    year: 2120,
    spring: {
      month: 2,
      day: 20,
      hour: 5,
      minute: 30,
      tod: "am",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 20,
      hour: 9,
      minute: 34,
      tod: "pm",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 22,
      hour: 2,
      minute: 8,
      tod: "pm",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 21,
      hour: 11,
      minute: 25,
      tod: "am",
      zone: "EST",
    },
  },
  {
    year: 2121,
    spring: {
      month: 2,
      day: 20,
      hour: 11,
      minute: 17,
      tod: "am",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 21,
      hour: 3,
      minute: 13,
      tod: "am",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 22,
      hour: 7,
      minute: 45,
      tod: "pm",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 21,
      hour: 5,
      minute: 13,
      tod: "pm",
      zone: "EST",
    },
  },
  {
    year: 2122,
    spring: {
      month: 2,
      day: 20,
      hour: 5,
      minute: 5,
      tod: "pm",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 21,
      hour: 9,
      minute: 4,
      tod: "am",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 23,
      hour: 1,
      minute: 41,
      tod: "am",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 21,
      hour: 11,
      minute: 2,
      tod: "pm",
      zone: "EST",
    },
  },
  {
    year: 2123,
    spring: {
      month: 2,
      day: 20,
      hour: 10,
      minute: 50,
      tod: "pm",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 21,
      hour: 2,
      minute: 51,
      tod: "pm",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 23,
      hour: 7,
      minute: 31,
      tod: "am",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 22,
      hour: 4,
      minute: 48,
      tod: "am",
      zone: "EST",
    },
  },
  {
    year: 2124,
    spring: {
      month: 2,
      day: 20,
      hour: 4,
      minute: 37,
      tod: "am",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 20,
      hour: 8,
      minute: 39,
      tod: "pm",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 22,
      hour: 1,
      minute: 20,
      tod: "pm",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 21,
      hour: 10,
      minute: 36,
      tod: "am",
      zone: "EST",
    },
  },
  {
    year: 2119,
    spring: {
      month: 2,
      day: 20,
      hour: 11,
      minute: 40,
      tod: "pm",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 21,
      hour: 3,
      minute: 37,
      tod: "pm",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 23,
      hour: 8,
      minute: 21,
      tod: "am",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 22,
      hour: 5,
      minute: 38,
      tod: "am",
      zone: "EST",
    },
  },
  {
    year: 2125,
    spring: {
      month: 2,
      day: 20,
      hour: 10,
      minute: 31,
      tod: "am",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 21,
      hour: 2,
      minute: 34,
      tod: "am",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 22,
      hour: 7,
      minute: 15,
      tod: "pm",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 21,
      hour: 4,
      minute: 33,
      tod: "pm",
      zone: "EST",
    },
  },
  {
    year: 2126,
    spring: {
      month: 2,
      day: 20,
      hour: 4,
      minute: 17,
      tod: "pm",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 21,
      hour: 8,
      minute: 12,
      tod: "am",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 23,
      hour: 1,
      minute: 1,
      tod: "am",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 21,
      hour: 10,
      minute: 27,
      tod: "pm",
      zone: "EST",
    },
  },
  {
    year: 2127,
    spring: {
      month: 2,
      day: 20,
      hour: 10,
      minute: 4,
      tod: "pm",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 21,
      hour: 2,
      minute: 3,
      tod: "pm",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 23,
      hour: 6,
      minute: 57,
      tod: "am",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 22,
      hour: 4,
      minute: 22,
      tod: "am",
      zone: "EST",
    },
  },
  {
    year: 2128,
    spring: {
      month: 2,
      day: 20,
      hour: 4,
      minute: 0,
      tod: "am",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 20,
      hour: 8,
      minute: 0,
      tod: "pm",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 22,
      hour: 12,
      minute: 47,
      tod: "pm",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 21,
      hour: 10,
      minute: 15,
      tod: "am",
      zone: "EST",
    },
  },
  {
    year: 2129,
    spring: {
      month: 2,
      day: 20,
      hour: 9,
      minute: 56,
      tod: "am",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 21,
      hour: 1,
      minute: 40,
      tod: "am",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 22,
      hour: 6,
      minute: 26,
      tod: "pm",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 21,
      hour: 4,
      minute: 3,
      tod: "pm",
      zone: "EST",
    },
  },
  {
    year: 2130,
    spring: {
      month: 2,
      day: 20,
      hour: 3,
      minute: 51,
      tod: "pm",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 21,
      hour: 7,
      minute: 31,
      tod: "am",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 23,
      hour: 12,
      minute: 22,
      tod: "am",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 21,
      hour: 9,
      minute: 54,
      tod: "pm",
      zone: "EST",
    },
  },
  {
    year: 2131,
    spring: {
      month: 2,
      day: 20,
      hour: 9,
      minute: 38,
      tod: "pm",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 21,
      hour: 1,
      minute: 24,
      tod: "pm",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 23,
      hour: 6,
      minute: 11,
      tod: "am",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 22,
      hour: 3,
      minute: 42,
      tod: "am",
      zone: "EST",
    },
  },
  {
    year: 2132,
    spring: {
      month: 2,
      day: 20,
      hour: 3,
      minute: 26,
      tod: "am",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 20,
      hour: 7,
      minute: 14,
      tod: "pm",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 22,
      hour: 11,
      minute: 54,
      tod: "am",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 21,
      hour: 9,
      minute: 28,
      tod: "am",
      zone: "EST",
    },
  },
  {
    year: 2133,
    spring: {
      month: 2,
      day: 20,
      hour: 9,
      minute: 17,
      tod: "am",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 21,
      hour: 1,
      minute: 8,
      tod: "am",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 22,
      hour: 5,
      minute: 46,
      tod: "pm",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 21,
      hour: 3,
      minute: 20,
      tod: "pm",
      zone: "EST",
    },
  },
  {
    year: 2134,
    spring: {
      month: 2,
      day: 20,
      hour: 3,
      minute: 3,
      tod: "pm",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 21,
      hour: 6,
      minute: 46,
      tod: "am",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 22,
      hour: 11,
      minute: 29,
      tod: "pm",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 21,
      hour: 9,
      minute: 5,
      tod: "pm",
      zone: "EST",
    },
  },
  {
    year: 2135,
    spring: {
      month: 2,
      day: 20,
      hour: 8,
      minute: 47,
      tod: "pm",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 21,
      hour: 12,
      minute: 32,
      tod: "pm",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 23,
      hour: 5,
      minute: 23,
      tod: "am",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 22,
      hour: 2,
      minute: 50,
      tod: "am",
      zone: "EST",
    },
  },
  {
    year: 2136,
    spring: {
      month: 2,
      day: 20,
      hour: 2,
      minute: 35,
      tod: "am",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 20,
      hour: 6,
      minute: 26,
      tod: "pm",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 22,
      hour: 11,
      minute: 14,
      tod: "am",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 21,
      hour: 8,
      minute: 39,
      tod: "am",
      zone: "EST",
    },
  },
  {
    year: 2137,
    spring: {
      month: 2,
      day: 20,
      hour: 8,
      minute: 23,
      tod: "am",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 21,
      hour: 12,
      minute: 2,
      tod: "am",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 22,
      hour: 4,
      minute: 49,
      tod: "pm",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 21,
      hour: 2,
      minute: 25,
      tod: "pm",
      zone: "EST",
    },
  },
  {
    year: 2138,
    spring: {
      month: 2,
      day: 20,
      hour: 2,
      minute: 6,
      tod: "pm",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 21,
      hour: 5,
      minute: 47,
      tod: "am",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 22,
      hour: 10,
      minute: 42,
      tod: "pm",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 21,
      hour: 8,
      minute: 19,
      tod: "pm",
      zone: "EST",
    },
  },
  {
    year: 2139,
    spring: {
      month: 2,
      day: 20,
      hour: 7,
      minute: 50,
      tod: "pm",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 21,
      hour: 11,
      minute: 36,
      tod: "am",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 23,
      hour: 4,
      minute: 30,
      tod: "am",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 22,
      hour: 2,
      minute: 8,
      tod: "am",
      zone: "EST",
    },
  },
  {
    year: 2140,
    spring: {
      month: 2,
      day: 20,
      hour: 1,
      minute: 39,
      tod: "am",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 20,
      hour: 5,
      minute: 20,
      tod: "pm",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 22,
      hour: 10,
      minute: 10,
      tod: "am",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 21,
      hour: 7,
      minute: 53,
      tod: "am",
      zone: "EST",
    },
  },
  {
    year: 2141,
    spring: {
      month: 2,
      day: 20,
      hour: 7,
      minute: 34,
      tod: "am",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 20,
      hour: 11,
      minute: 12,
      tod: "pm",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 22,
      hour: 4,
      minute: 4,
      tod: "pm",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 21,
      hour: 1,
      minute: 47,
      tod: "pm",
      zone: "EST",
    },
  },
  {
    year: 2142,
    spring: {
      month: 2,
      day: 20,
      hour: 1,
      minute: 26,
      tod: "pm",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 21,
      hour: 4,
      minute: 54,
      tod: "am",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 22,
      hour: 9,
      minute: 50,
      tod: "pm",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 21,
      hour: 7,
      minute: 35,
      tod: "pm",
      zone: "EST",
    },
  },
  {
    year: 2143,
    spring: {
      month: 2,
      day: 20,
      hour: 7,
      minute: 13,
      tod: "pm",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 21,
      hour: 10,
      minute: 44,
      tod: "am",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 23,
      hour: 3,
      minute: 42,
      tod: "am",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 22,
      hour: 1,
      minute: 24,
      tod: "am",
      zone: "EST",
    },
  },
  {
    year: 2144,
    spring: {
      month: 2,
      day: 20,
      hour: 1,
      minute: 3,
      tod: "am",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 20,
      hour: 4,
      minute: 45,
      tod: "pm",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 22,
      hour: 9,
      minute: 36,
      tod: "am",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 21,
      hour: 7,
      minute: 20,
      tod: "am",
      zone: "EST",
    },
  },
  {
    year: 2145,
    spring: {
      month: 2,
      day: 20,
      hour: 6,
      minute: 59,
      tod: "am",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 20,
      hour: 10,
      minute: 28,
      tod: "pm",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 22,
      hour: 3,
      minute: 14,
      tod: "pm",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 21,
      hour: 1,
      minute: 6,
      tod: "pm",
      zone: "EST",
    },
  },
  {
    year: 2146,
    spring: {
      month: 2,
      day: 20,
      hour: 12,
      minute: 45,
      tod: "pm",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 21,
      hour: 4,
      minute: 16,
      tod: "am",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 22,
      hour: 9,
      minute: 10,
      tod: "pm",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 21,
      hour: 6,
      minute: 58,
      tod: "pm",
      zone: "EST",
    },
  },
  {
    year: 2147,
    spring: {
      month: 2,
      day: 20,
      hour: 6,
      minute: 35,
      tod: "pm",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 21,
      hour: 10,
      minute: 10,
      tod: "am",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 23,
      hour: 3,
      minute: 6,
      tod: "am",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 22,
      hour: 12,
      minute: 48,
      tod: "am",
      zone: "EST",
    },
  },
  {
    year: 2148,
    spring: {
      month: 2,
      day: 20,
      hour: 12,
      minute: 25,
      tod: "am",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 20,
      hour: 3,
      minute: 58,
      tod: "pm",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 22,
      hour: 8,
      minute: 49,
      tod: "am",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 21,
      hour: 6,
      minute: 33,
      tod: "am",
      zone: "EST",
    },
  },
  {
    year: 2149,
    spring: {
      month: 2,
      day: 20,
      hour: 6,
      minute: 15,
      tod: "am",
      zone: "EDT",
    },
    summer: {
      month: 5,
      day: 20,
      hour: 9,
      minute: 50,
      tod: "pm",
      zone: "EDT",
    },
    fall: {
      month: 8,
      day: 22,
      hour: 2,
      minute: 45,
      tod: "pm",
      zone: "EDT",
    },
    winter: {
      month: 11,
      day: 21,
      hour: 12,
      minute: 32,
      tod: "pm",
      zone: "EST",
    },
  },
];

export default seasonData;
